name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/modules/model_sentiment_analysis.py"  # Trigger only if this file is modified
      - "src/modules/data_processor.py"  # Trigger only if this file is modified
      - "src/modules/transformer_components.py"
      - "src/translation_french_english.py"
  pull_request:
    branches:
      - main
    paths:
      - "src/modules/model_sentiment_analysis.py"  # Trigger only if this file is modified
      - "src/modules/data_processor.py"  # Trigger only if this file is modified
      - "src/modules/transformer_components.py"
      - "src/translation_french_english.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          uv sync --extra dev

      # Run code quality checks
      - name: Run code quality checks
        run: |
          uv run ruff check ./src ./app ./tests
          uv run ruff format --check ./src ./app ./tests

      # Run pytest
      - name: Run tests with pytest
        run: |
          uv run pytest