name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/modules/model_sentiment_analysis.py"  # Trigger only if this file is modified
      - "src/modules/data_processor.py"  # Trigger only if this file is modified
      - "src/modules/transformer_component.py"
      - "src/translation_french_english.py"
  pull_request:
    branches:
      - main
    paths:
      - "src/modules/model_sentiment_analysis.py"  # Trigger only if this file is modified
      - "src/modules/data_processor.py"  # Trigger only if this file is modified
      - "src/modules/transformer_component.py"
      - "src/translation_french_english.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without macos --without pyaudio --without kaggle

      # Run pytest
      - name: Run tests with pytest
        run: |
          poetry run pytest